# Generated by Django 3.2.7 on 2022-01-15 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Book Name')),
                ('pdf', models.FileField(null=True, upload_to='pdf/', verbose_name='Pdf File')),
                ('viewed_time', models.IntegerField(default=0, verbose_name='Total_Viewed_Seconds')),
                ('open_time', models.DateTimeField(null=True, verbose_name='Pdf_Open_Time')),
                ('close_time', models.DateTimeField(null=True, verbose_name='Pdf_Close_Time')),
                ('user', models.ForeignKey(on_delete=models.SET('User Deleted'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, null=True, verbose_name='Tag')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
            options={
                'verbose_name': 'Book Tags',
            },
        ),
        migrations.CreateModel(
            name='SharedWithMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to='Books.book')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
